## Lecture 01 Python juypter notebook
### Use Spyder or Canopy Editor to create a new juypter (ipython) notebook

Jupyter notebooks are useful for debugging and exploring. Use Jupyter notebooks to explore how Python works, expolore data, and to learn new functions.

Jupyter notebooks and ipython are useful for figuring things out, but I want your HW to be submitted as a single *_py2.py* or *_py3.py* file. Where *.py* files are Python scripts.

### Be careful with pointers

In [4]:
x = [0,1,2]
y = x
x[0] = 3
print(x)
print(y)

[3, 1, 2]
[3, 1, 2]


In [1]:
import numpy as np
x = np.array([10])
y = x
z = x.copy()
#x = x + 10
x += 10
print(x,y,z)
x = x + 5
print(x,y)

(array([20]), array([20]), array([10]))
(array([25]), array([20]))


In [8]:
x = x + 10
print(x,y,z)

(array([30]), array([20]), array([10]))


### Be careful with Division!!!

In [9]:
a = 3
b = 2
print(a/b)

1


In [46]:
from __future__ import division
'''
this line imports Python 3 division into Python 2
if you are using a script, these __future__
must be the first things in your Python script
''' 

a = 3
b = 2
print(a/b)
print(a//b)

1.5
1


In [12]:
a = 4
b = 2
c = a/b
print(c,type(c))

(2.0, <type 'float'>)


In [13]:
x[0.0]

/usr/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  """Entry point for launching an IPython kernel.


30

In [22]:
print(0 == False)
print(1 == False)
print(0 == True)
print(1 == True)

True
False
False
True


### Floating point precission rounding error

In [23]:
0.1 + 0.2 == 0.3

False

In [25]:
np.isclose(0.1+0.2, 0.3)

True

### Sets

In [26]:
{1,2,3}

{1, 2, 3}

In [27]:
{1,5,5,5,2}

{1, 2, 5}

In [28]:
[1,2,3]

[1, 2, 3]

### Dictionary

In [33]:
param = {a:'hello'}
param[b] = 'hi'
print(param)

{2: 'hi', 4: 'hello'}


### Assigning new values at any time

In [34]:
a = None
b = None
a = 1

In [35]:
a


1

### The append function is soooooo useful
### We have lists in lists in lists

In [37]:
x = []
x.append(1)
x.append(2)
x.append(3)
x.append('string')
x.append([3,4,4,[1,2,2,3,3,0]])
print(x)

[1, 2, 3, 'string', [3, 4, 4, [1, 2, 2, 3, 3, 0]]]


In [38]:
x[4]

[3, 4, 4, [1, 2, 2, 3, 3, 0]]

In [39]:
x[4][3]

[1, 2, 2, 3, 3, 0]

In [40]:
x[4][3][3]

3

In [47]:
x = 2
if x < 3:

    print('x is 3')
    print('end of the code block')
print('outside code block')

x is 3
end of the code block
outside code block


### This is how you can continue onto another line

In [44]:
x = 1 + 3 + \
2+4
print(x)

10


### If y is a tuple, you can assign y a new value, despite being a tuple
The thing with tuples is that you can't change the 

In [45]:
y = (1,2,3)
y = None
print(y)

None
