In [1]:
# Lecuture 04

In [2]:
from __future__ import print_function
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import_tools',
 '_mat',
 'abs',
 'absolute',
 'absolute

In [4]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


In [31]:
np.random.random?

In [5]:
z = np.array([2,2])
print(z)

[2 2]


In [6]:
x = [1,2,2]
y = np.array(x)
print(y)

[1 2 2]


In [7]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
aa = [1,2,[2,3]]
np.array(aa)

ValueError: setting an array element with a sequence.

In [9]:
y.dtype

dtype('int64')

In [10]:
y

array([1, 2, 2])

In [11]:
z = np.zeros((3,3),dtype='float64')
print(z)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [12]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
z.ndim

2

In [14]:
z.shape

(3, 3)

In [15]:
z.size

9

In [16]:
a = np.array([1,2,3,3])
b = a.T
print(a.shape,b.shape)

(4,) (4,)


In [22]:
x = np.array([[1.,2,3],[2,3,4]])
y = np.array([[4.,5,6],[3,4,5]])
z = np.array([[0],[1],[2]])

print(z.shape)

(3, 1)


In [24]:
z = np.concatenate((x,y))
print(z, z.shape)

[[ 1.  2.  3.]
 [ 2.  3.  4.]
 [ 4.  5.  6.]
 [ 3.  4.  5.]] (4, 3)


In [29]:
f = z.flatten()
print(f, f.shape)

[ 1.  2.  3.  2.  3.  4.  4.  5.  6.  3.  4.  5.] (12,)


In [30]:
print(z)

[[ 1.  2.  3.]
 [ 2.  3.  4.]
 [ 4.  5.  6.]
 [ 3.  4.  5.]]
